Replace Ktor Android engine with OkHttp to fix HttpTimeout crash
The Android engine was trying to load HttpTimeout plugin which wasn't
available in the classpath, causing NoClassDefFoundError.

Changed from ktor-client-android to ktor-client-okhttp:
- Removed ktor-client-android
- Removed ktor-utils (not needed)
- Added ktor-client-okhttp (more stable, better Android support)

OkHttp is the recommended HTTP engine for Android apps and doesn't
have the HttpTimeout dependency issue.

This should resolve:
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/plugins/HttpTimeout